# Generated by Django 3.2.3 on 2021-05-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20210524_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='cart',
            new_name='user',
        ),
    ]
